package io.unitycatalog.server.service.lance;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.linecorp.armeria.common.HttpResponse;
import com.linecorp.armeria.server.annotation.ExceptionHandler;
import com.linecorp.armeria.server.annotation.Param;
import com.linecorp.armeria.server.annotation.Post;
import io.unitycatalog.server.auth.UnityCatalogAuthorizer;
import io.unitycatalog.server.exception.BaseException;
import io.unitycatalog.server.exception.ErrorCode;
import io.unitycatalog.server.persist.LanceVersionRepository;
import io.unitycatalog.server.persist.Repositories;
import io.unitycatalog.server.persist.dao.LanceVersionDAO;
import java.util.List;
import java.util.Optional;

@ExceptionHandler(LanceExceptionHandler.class)
public class LanceRestVersionService {
  private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

  private final LanceTableResolver tableResolver;
  private final LanceVersionRepository versionRepository;
  private final LanceAuthorizationService authorizationService;

  public LanceRestVersionService(Repositories repositories, UnityCatalogAuthorizer authorizer) {
    this.tableResolver = new LanceTableResolver(repositories);
    this.versionRepository = repositories.getLanceVersionRepository();
    this.authorizationService = new LanceAuthorizationService(repositories, authorizer);
  }

  @Post("/v1/table/{id}/version/list")
  public HttpResponse listVersions(
      @Param("id") String id,
      @Param("delimiter") Optional<String> delimiter,
      VersionListRequest request) {
    ResolvedLanceTable table = resolveNativeTable(id, delimiter.orElse(null), "version history");
    authorizationService.authorizeReadTable(table.assetDAO());

    Integer safeLimit = safeLimit(request == null ? null : request.pageSize());
    List<LanceVersionDAO> versions =
        versionRepository.listVersions(
            table.assetDAO().getId(),
            optionalLong(request == null ? null : request.startVersion()),
            optionalLong(request == null ? null : request.endVersion()),
            safeLimit == null ? Optional.empty() : Optional.of(safeLimit),
            optionalLong(request == null ? null : request.pageToken()));

    String nextPageToken = null;
    if (safeLimit != null && versions.size() > safeLimit) {
      nextPageToken = String.valueOf(versions.get(safeLimit - 1).getVersion());
      versions = versions.subList(0, safeLimit);
    }

    return HttpResponse.ofJson(
        new VersionListResponse(
            versions.stream().map(this::toVersionView).toList(), nextPageToken));
  }

  @Post("/v1/table/{id}/version/describe")
  public HttpResponse describeVersion(
      @Param("id") String id,
      @Param("delimiter") Optional<String> delimiter,
      VersionDescribeRequest request) {
    ResolvedLanceTable table = resolveNativeTable(id, delimiter.orElse(null), "version metadata");
    authorizationService.authorizeReadTable(table.assetDAO());
    Long version = request == null ? null : request.version();
    if (version == null) {
      throw new BaseException(ErrorCode.INVALID_ARGUMENT, "Lance version is required.");
    }
    LanceVersionDAO versionDAO =
        versionRepository
            .findVersion(table.assetDAO().getId(), version)
            .orElseThrow(
                () ->
                    new BaseException(ErrorCode.NOT_FOUND, "Lance version not found: " + version));
    return HttpResponse.ofJson(toVersionView(versionDAO));
  }

  @Post("/v1/table/{id}/version/create")
  public HttpResponse createVersion(@Param("id") String id, Object ignored) {
    throw new BaseException(
        ErrorCode.INVALID_ARGUMENT,
        "Lance versions are generated by table writes and cannot be created manually.");
  }

  @Post("/v1/table/batch-create-versions")
  public HttpResponse batchCreateVersions(Object ignored) {
    throw new BaseException(
        ErrorCode.INVALID_ARGUMENT,
        "Lance versions are generated by table writes and cannot be batch-created manually.");
  }

  @Post("/v1/table/{id}/version/delete")
  public HttpResponse deleteVersions(@Param("id") String id, Object ignored) {
    throw new BaseException(
        ErrorCode.UNIMPLEMENTED,
        "deleteVersions requires Lance execution backend support before metadata can be updated.");
  }

  private ResolvedLanceTable resolveNativeTable(String id, String delimiter, String operation) {
    ResolvedLanceTable table = tableResolver.resolve(id, delimiter);
    if (table.legacyBridge()) {
      throw new BaseException(
          ErrorCode.UNIMPLEMENTED, "Legacy bridge Lance tables do not support " + operation + ".");
    }
    return table;
  }

  private VersionView toVersionView(LanceVersionDAO versionDAO) {
    return new VersionView(
        versionDAO.getVersion(),
        versionDAO.getOperation(),
        timestamp(versionDAO),
        versionDAO.getManifestPath(),
        versionDAO.getManifestSize(),
        versionDAO.getEtag(),
        parseJson(versionDAO.getMetadataJson(), "version metadata_json"),
        parseJson(versionDAO.getStatsJson(), "version stats_json"),
        versionDAO.getCreatedBy(),
        versionDAO.getCreatedAt() == null
            ? null
            : versionDAO.getCreatedAt().toInstant().toString());
  }

  private Object parseJson(String json, String fieldName) {
    if (json == null || json.isBlank()) {
      return null;
    }
    try {
      return OBJECT_MAPPER.readValue(json, Object.class);
    } catch (JsonProcessingException e) {
      throw new BaseException(ErrorCode.INTERNAL, "Invalid persisted Lance " + fieldName + ".", e);
    }
  }

  private String timestamp(LanceVersionDAO versionDAO) {
    return versionDAO.getTimestamp() == null
        ? null
        : versionDAO.getTimestamp().toInstant().toString();
  }

  private Integer safeLimit(Integer limit) {
    return limit != null && limit > 0 ? limit : null;
  }

  private Optional<Long> optionalLong(Long value) {
    return value == null ? Optional.empty() : Optional.of(value);
  }

  public record VersionListRequest(
      @JsonProperty("page_token") Long pageToken,
      @JsonProperty("page_size") Integer pageSize,
      @JsonProperty("start_version") Long startVersion,
      @JsonProperty("end_version") Long endVersion) {}

  public record VersionDescribeRequest(Long version) {}

  public record VersionListResponse(
      List<VersionView> versions, @JsonProperty("next_page_token") String nextPageToken) {}

  @JsonInclude(JsonInclude.Include.NON_NULL)
  public record VersionView(
      Long version,
      String operation,
      String timestamp,
      @JsonProperty("manifest_path") String manifestPath,
      @JsonProperty("manifest_size") Long manifestSize,
      String etag,
      Object metadata,
      Object stats,
      @JsonProperty("created_by") String createdBy,
      @JsonProperty("created_at") String createdAt) {}
}
